const $ = (id) => document.getElementById(id);
let root = ''; let running = false; let savedAvailable = false;
const UI_SETTINGS_KEY = 'ecommerce-main-image-generator.ui-settings.v1';
const clampInt = (value, min, max, fallback) => { const numeric = Number(value); return Math.max(min, Math.min(max, Math.trunc(Number.isFinite(numeric) ? numeric : fallback))); };
function currentUiPreferences() {
  const waitMinSeconds = clampInt($('waitMinSeconds').value, 0, 600, 0);
  const waitMaxSeconds = Math.max(waitMinSeconds, clampInt($('waitMaxSeconds').value, 0, 600, 0));
  return { settingsVersion: 4, totalCycles: clampInt($('totalCycles').value, 1, 99, 1), waitEnabled: $('waitEnabled').checked, waitMinSeconds, waitMaxSeconds, generationTimeoutSeconds: clampInt($('generationTimeoutSeconds').value, 10, 600, 200), ignoredCheckEveryChats: clampInt($('ignoredCheckEveryChats').value, 1, 20, 10), adaptiveScheduling: $('adaptiveScheduling').checked, qualityPolicy: { enabled: $('qualityEnabled').checked, minDimension: clampInt($('minDimension').value, 256, 2048, 512), requireWhite: $('requireWhite').checked, strictConsistency: $('strictConsistency').checked }, creativePolicy: { enabled: $('creativeEnabled').checked, globalRequirements: $('globalCreativeRequirements').value.slice(0, 4000) } };
}
function saveUiPreferences() { try { localStorage.setItem(UI_SETTINGS_KEY, JSON.stringify(currentUiPreferences())); } catch {} }
function loadUiPreferences() {
  try {
    const saved = JSON.parse(localStorage.getItem(UI_SETTINGS_KEY) || 'null'); if (!saved) { $('ignoredCheckEveryChats').value = 10; return; }
    $('totalCycles').value = clampInt(saved.totalCycles, 1, 99, 1); $('waitEnabled').checked = saved.waitEnabled !== false;
    $('waitMinSeconds').value = clampInt(saved.waitMinSeconds, 0, 600, 20); $('waitMaxSeconds').value = Math.max(Number($('waitMinSeconds').value), clampInt(saved.waitMaxSeconds, 0, 600, 60));
    $('generationTimeoutSeconds').value = clampInt(saved.generationTimeoutSeconds, 10, 600, 200); $('ignoredCheckEveryChats').value = !saved.settingsVersion && Number(saved.ignoredCheckEveryChats) === 5 ? 10 : clampInt(saved.ignoredCheckEveryChats, 1, 20, 10); $('adaptiveScheduling').checked = saved.adaptiveScheduling !== false; $('qualityEnabled').checked = saved.qualityPolicy?.enabled !== false; $('minDimension').value = clampInt(saved.qualityPolicy?.minDimension, 256, 2048, 512); $('requireWhite').checked = saved.qualityPolicy?.requireWhite === true; $('strictConsistency').checked = saved.qualityPolicy?.strictConsistency === true; $('creativeEnabled').checked = saved.creativePolicy?.enabled !== false; $('globalCreativeRequirements').value = String(saved.creativePolicy?.globalRequirements || '').slice(0, 4000);
  } catch { localStorage.removeItem(UI_SETTINGS_KEY); }
}
function unlockApplication() { $('authOverlay').classList.add('hidden'); $('appMain').classList.remove('appLocked'); $('appMain').setAttribute('aria-hidden', 'false'); $('adminPassword').value = ''; loadUpdateUi(); }
async function submitAdminLogin() {
  if ($('adminLogin').disabled) return;
  const account = $('adminAccount').value.trim(); const password = $('adminPassword').value; $('authError').textContent = ''; $('adminLogin').disabled = true;
  try { const result = await window.appApi.adminLogin(account, password); if (result.ok) unlockApplication(); else { $('authError').textContent = result.message || '账号或密码错误'; $('adminPassword').value = ''; $('adminPassword').focus(); } }
  catch (error) { $('authError').textContent = `登录失败：${error.message}`; }
  finally { $('adminLogin').disabled = false; }
}
$('adminLogin').onclick = submitAdminLogin;
for (const id of ['adminAccount', 'adminPassword']) $(id).addEventListener('keydown', (event) => { if (event.key === 'Enter') submitAdminLogin(); });
window.appApi.authStatus().then((status) => { if (status.authenticated) unlockApplication(); else $('adminAccount').focus(); }).catch((error) => { $('authError').textContent = `无法检查授权状态：${error.message}`; });
function requireRoot() { if (!root) { alert('请先选择产品总目录'); return false; } return true; }
function appendLog(line) { const el = $('log'); if (el.textContent === '等待开始…') el.textContent = ''; el.textContent += `${line}\n`; el.scrollTop = el.scrollHeight; }
function formatSeconds(n) { if (!Number.isFinite(n)) return '—'; const seconds = Math.max(0, Math.ceil(n)); return `${String(Math.floor(seconds / 60)).padStart(2,'0')}:${String(seconds % 60).padStart(2,'0')}`; }
function waitOptions() { const enabled = $('waitEnabled').checked; const min = Math.max(0, Math.min(600, Math.trunc(Number($('waitMinSeconds').value) || 0))); const max = Math.max(min, Math.min(600, Math.trunc(Number($('waitMaxSeconds').value) || 0))); $('waitMinSeconds').value = min; $('waitMaxSeconds').value = max; return { waitEnabled: enabled, waitMinSeconds: min, waitMaxSeconds: max }; }
function generationOptions() { const generationTimeoutSeconds = Math.max(10, Math.min(600, Math.trunc(Number($('generationTimeoutSeconds').value) || 200))); const ignoredCheckEveryChats = Math.max(1, Math.min(20, Math.trunc(Number($('ignoredCheckEveryChats').value) || 10))); $('generationTimeoutSeconds').value = generationTimeoutSeconds; $('ignoredCheckEveryChats').value = ignoredCheckEveryChats; return { generationTimeoutSeconds, ignoredCheckEveryChats }; }
function advancedOptions() { return { adaptiveScheduling: $('adaptiveScheduling').checked, qualityPolicy: { enabled: $('qualityEnabled').checked, minDimension: clampInt($('minDimension').value, 256, 2048, 512), requireWhite: $('requireWhite').checked, strictConsistency: $('strictConsistency').checked }, creativePolicy: { enabled: $('creativeEnabled').checked, globalRequirements: $('globalCreativeRequirements').value.slice(0, 4000) } }; }
function refreshWaitUi() { const { waitEnabled, waitMinSeconds, waitMaxSeconds } = waitOptions(); $('waitMinSeconds').disabled = running || !waitEnabled; $('waitMaxSeconds').disabled = running || !waitEnabled; $('waitSummary').textContent = waitEnabled ? `轮次间随机 ${waitMinSeconds}–${waitMaxSeconds} 秒` : '轮次等待已关闭'; }
async function refreshSavedState() { if (!root) return; const state = await window.appApi.inspectSaved(root); savedAvailable = !!state.available; $('continueSaved').disabled = running || !savedAvailable; if (savedAvailable) { $('totalCycles').value = state.totalCycles || 1; $('waitEnabled').checked = state.waitEnabled !== false; $('waitMinSeconds').value = state.waitMinSeconds ?? 20; $('waitMaxSeconds').value = state.waitMaxSeconds ?? 60; $('generationTimeoutSeconds').value = state.generationTimeoutSeconds ?? 200; $('ignoredCheckEveryChats').value = state.ignoredCheckEveryChats ?? 10; $('adaptiveScheduling').checked = state.adaptiveScheduling !== false; $('qualityEnabled').checked = state.qualityPolicy?.enabled !== false; $('minDimension').value = state.qualityPolicy?.minDimension || 512; $('requireWhite').checked = state.qualityPolicy?.requireWhite === true; $('strictConsistency').checked = state.qualityPolicy?.strictConsistency === true; $('creativeEnabled').checked = state.creativePolicy?.enabled !== false; $('globalCreativeRequirements').value = String(state.creativePolicy?.globalRequirements || '').slice(0, 4000); refreshWaitUi(); saveUiPreferences(); $('cycleStatus').textContent = `当前批次 ${state.currentCycle || 1} / ${state.totalCycles || 1}`; appendLog(`检测到可继续任务：${state.runId}`); } }
$('choose').onclick = async () => { const chosen = await window.appApi.chooseFolder(); if (chosen) { root = chosen; $('root').value = root; await refreshSavedState(); } };
$('output').onclick = () => requireRoot() && window.appApi.openOutput(root);
$('login').onclick = async () => { if (!requireRoot()) return; appendLog('正在连接当前已打开的 ChatGPT Edge 窗口…'); try { const r = await window.appApi.login(root); appendLog(r.loggedIn ? '已连接，ChatGPT 登录状态正常' : '已找到 Edge，但尚未检测到可用的 ChatGPT 输入框'); } catch (e) { appendLog(`连接失败：${e.message}`); } };
$('start').onclick = async () => { if (!requireRoot()) return; const totalCycles = Math.max(1, Math.min(99, Math.trunc(Number($('totalCycles').value) || 1))); const waits = waitOptions(); const generation = generationOptions(); const advanced = advancedOptions(); $('totalCycles').value = totalCycles; saveUiPreferences(); if (savedAvailable && !confirm('开始新任务会按设置的循环次数创建多批输出目录；上次断点仍保留但不再作为当前任务。确定开始？')) return; running = true; savedAvailable = false; refreshWaitUi(); await window.appApi.startNew(root, { totalCycles, ...waits, ...generation, ...advanced }); };
$('continueSaved').onclick = async () => { if (!requireRoot() || !savedAvailable) return; const waits = waitOptions(); const generation = generationOptions(); const advanced = advancedOptions(); saveUiPreferences(); running = true; refreshWaitUi(); await window.appApi.continueSaved(root, { ...waits, ...generation, ...advanced }); };
$('pause').onclick = () => window.appApi.pause(); $('resume').onclick = () => window.appApi.resume(); $('stop').onclick = () => confirm('停止后会保留已生成图片和断点进度。确定停止？') && window.appApi.stop();
loadUiPreferences();
saveUiPreferences();
for (const id of ['totalCycles', 'waitEnabled', 'waitMinSeconds', 'waitMaxSeconds', 'generationTimeoutSeconds', 'ignoredCheckEveryChats', 'adaptiveScheduling', 'qualityEnabled', 'minDimension', 'requireWhite', 'strictConsistency', 'creativeEnabled', 'globalCreativeRequirements']) $(id).addEventListener('change', () => { refreshWaitUi(); saveUiPreferences(); });
$('globalCreativeRequirements').addEventListener('input', saveUiPreferences);
refreshWaitUi();
$('clear').onclick = () => $('log').textContent = '';
window.appApi.onLog(appendLog);
window.appApi.onStatus((s) => {
  const wasRunning = running; running = s.running; $('stateBadge').textContent = s.phase || (s.running ? '运行中' : '待处理');
  $('product').textContent = s.product || '—'; $('productCount').textContent = `${s.productIndex || 0} / ${s.productTotal || 0}`;
  $('round').textContent = s.round ? `${s.round} / 10` : '—'; $('detectedImages').textContent = `本轮识别 ${Number.isFinite(s.detectedImages) && s.detectedImages > 0 ? s.detectedImages : '—'} / 5 张`; $('completed').textContent = `${s.completed || 0} / 50`; $('countdown').textContent = formatSeconds(s.remainingSeconds); $('cycleStatus').textContent = `当前批次 ${s.currentCycle || 0} / ${s.totalCycles || Number($('totalCycles').value) || 1}`;
  $('runtimeMetrics').textContent = `当前步骤：${s.workflowStep || s.phase || '—'}`; $('adaptiveMetrics').textContent = `本对话等待：${s.adaptiveGenerationSeconds || '—'}秒；自适应间隔：${s.adaptiveDelaySeconds || '—'}秒；近期失败率：${Math.round((s.recentFailureRate || 0) * 100)}%；质量拒绝：${s.qualityRejected || 0}，提示：${s.qualityWarnings || 0}`;
  $('start').disabled = !!s.running; $('continueSaved').disabled = !!s.running || !savedAvailable; $('choose').disabled = !!s.running; $('totalCycles').disabled = !!s.running; $('waitEnabled').disabled = !!s.running; $('generationTimeoutSeconds').disabled = !!s.running; $('ignoredCheckEveryChats').disabled = !!s.running; $('adaptiveScheduling').disabled = !!s.running; $('qualityEnabled').disabled = !!s.running; $('minDimension').disabled = !!s.running; $('requireWhite').disabled = !!s.running; $('strictConsistency').disabled = !!s.running; $('creativeEnabled').disabled = !!s.running; $('globalCreativeRequirements').disabled = !!s.running; refreshWaitUi(); $('pause').disabled = !s.running || s.paused; $('resume').disabled = !s.running || !s.paused; $('stop').disabled = !s.running; $('checkUpdate').disabled = !!s.running; $('chooseUpdateSource').disabled = !!s.running;
  if (wasRunning && !running) refreshSavedState().catch(() => {});
});
async function loadUpdateUi() { try { $('appVersion').textContent = `当前版本 v${await window.appApi.getVersion()}`; const settings = await window.appApi.getUpdateSettings(); $('updateSource').value = settings.source || ''; $('autoCheckUpdate').checked = settings.autoCheck !== false; } catch (error) { $('appVersion').textContent = '版本读取失败'; $('updateStatus').textContent = error.message; } }
$('chooseUpdateSource').onclick = async () => { try { const source = await window.appApi.chooseUpdateSource(); if (!source) return; $('updateSource').value = source; await window.appApi.saveUpdateSettings({ source, autoCheck: $('autoCheckUpdate').checked }); $('updateStatus').textContent = '更新源已保存，可以检查更新'; } catch (error) { $('updateStatus').textContent = `选择失败：${error.message}`; } };
$('checkUpdate').onclick = async () => { try { await window.appApi.saveUpdateSettings({ source: $('updateSource').value.trim(), autoCheck: $('autoCheckUpdate').checked }); const result = await window.appApi.checkUpdate($('updateSource').value.trim()); $('updateStatus').textContent = result.message; $('installUpdate').disabled = result.state !== 'ready'; } catch (error) { $('updateStatus').textContent = `检查失败：${error.message}`; } };
$('installUpdate').onclick = async () => { if (!confirm('安装更新会关闭并重新打开软件，任务设置和断点会保留。现在安装？')) return; try { await window.appApi.installUpdate(); } catch (error) { $('updateStatus').textContent = `安装失败：${error.message}`; } };
$('autoCheckUpdate').onchange = () => window.appApi.saveUpdateSettings({ source: $('updateSource').value.trim(), autoCheck: $('autoCheckUpdate').checked }).catch((error) => { $('updateStatus').textContent = error.message; });
window.appApi.onUpdateStatus((status) => { $('updateStatus').textContent = status.message || status.state; $('installUpdate').disabled = status.state !== 'ready' || running; });
